# Generated by Django 3.0.5 on 2020-04-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_cartentry_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartEntry',
        ),
    ]
