# Generated by Django 3.0.5 on 2020-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartentry',
            name='name',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
