# Generated by Django 3.0.5 on 2020-04-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartentry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartentry',
            name='name',
        ),
    ]
