# Generated by Django 3.0.5 on 2020-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_cartentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartentry',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
