# Generated by Django 3.0.5 on 2020-04-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartentry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
